### ISSUE TITLE
Automatically approve users

### ISSUE THREAD

**Issue by hameno** [o360/backend#67]
### Description
We want to use this tool with a custom LDAP backend but we noticed in our tests that an admin always has to approve the newly logged in users. Since only allowed users are able to sign-in we would like to disable this approval process and immediately allow access for the users.
I couldn't find any such option/config. Could you maybe add this?

### Acceptance criteria:
New users are automatially approved when auth has been configured like this.

**Comment by maximskripnik** [comment]
Hello and thanks for the feedback!

Ye, it was an intentional design choice for the behaviour to be like that, if I remember correctly, so no wonder you could not find such option.
But it's definitely possible to add an option to disable the mandatory approval. @bwsw What do you think? I could implement this I think if you decide that it's for the better

**Comment by hameno** [comment]
That would be great 👍

**Comment by bwsw** [comment]
@maximskripnik it would be great if you could implement it as an optional feature.

**Comment by maximskripnik** [comment]
@hameno Please try the latest published docker image and let me know if it works as you expected (see the updated documentation notes)

**Comment by hameno** [comment]
Yes, works perfectly. Thanks alot 👍
